### ISSUE TITLE
 Payment Information iframe behaviour

### ISSUE THREAD

**Issue by ddpkts** [wallee-payment/oxid-6.0#3]
Hey, when I select Wallee payment method e.g. `Credit / Debit card (Onsite)` - `Payment Information` iframe appears on order confirmation page (that's cool!), but when I click submit button with empty fields, fields are being marked as red (invalid) and the form is being submitted - I am redirected to `cl=payment&payerror=-1&payerrortext=WALLEE_PENDING`, second time I try to submit - I get to thank you page.

What's the expected behaviour here? I expect form submit should be prevented on invalid form.

**Comment by sbossert** [comment]
Hi,
There was an error which did not prevent the form from being submitted when empty, this has been fixed in the latest release.
